version: '3'
services:
  vue-cli:
    build: .
    container_name: app-nuxtjs
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "3000:3000"
    command: tail -f /dev/null
    stdin_open: true
    tty: true
